### ISSUE TITLE
Please Enable tis Feture: msVideoTranslateOverlayButton

### ISSUE THREAD

**Issue by Soliver84** [HotCakeX/MSEdgeFeatures#21]
Hello

Please Enable tis Feture: msVideoTranslateOverlayButton

**Comment by HotCakeX** [comment]
Hi,
Thank you, i just did it and made a post about it: https://github.com/HotCakeX/MSEdgeFeatures/discussions/22

**Comment by Soliver84** [comment]
Can you provide me with the exe version in which everything works?

I can't find the download for it anywhere?

Was the function renamed at some point

**Comment by HotCakeX** [comment]
> Can you provide me with the exe version in which everything works?
> 
> I can't find the download for it anywhere?
> 
> Was the function renamed at some point
> 
> I don't know how to get to the function? https://x.com/Leopeva64/status/1787378026709131409

You don't need any exe. All you have to do is install Edge canary latest version then follow the instructions at this page: https://github.com/HotCakeX/MSEdgeFeatures/releases/tag/122.0.2359.0

The how to use section on the readme also provides more details:
https://github.com/HotCakeX/MSEdgeFeatures?tab=readme-ov-file#how-to-use--

**Comment by HotCakeX** [comment]
I did try it and posted screenshots on in the discussions

Here is another easy way. Right-click on Edge canary's icon on desktop, in the "Target" field, go all the way to the end and then paste this ` --enable-features=msTranslateVideo,msTranslateVideoCaption`

<br>

<img width="314" alt="image" src="https://github.com/HotCakeX/MSEdgeFeatures/assets/118815227/e2ac7f5b-4b3e-4b23-b004-45dab7300ed7">

<br>

This feature is coming to everyone very soon. All features first come to the Canary channel, then Dev channel, then Beta channel and finally available to everyone in the Stable channel.

You won't miss the change to use it so nothing to worry about 🙂
